# Generated by Django 3.1 on 2020-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0003_auto_20200830_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='key',
            field=models.TextField(unique=True),
        ),
    ]
