# Generated by Django 3.1 on 2020-08-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0004_auto_20200830_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='key',
            field=models.TextField(help_text='Add any random characters of your choice to shorten it.', unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='original_url',
            field=models.URLField(help_text='Add the original URL that you want to shorten.'),
        ),
    ]
